name: Build and Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Build with Maven
      run: mvn clean package

    - name: Package with jpackage
      run: |
        jpackage --input target --name ForestPixel --main-jar forestpixel-1.0-SNAPSHOT.jar --main-class org.maggdadev.forestpixel.Main --type exe
    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        path: ./forestvendetta/build/distributions/consoleapp-0.0.1.msi
        name: windows-installer
        retention-days: 1
        
