name: Build and Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        java-package: jdk+fx
        distribution: 'zulu'

    - name: Build with Maven
      run: mvn clean package
    - name: Create runtime image using jlink
      run: |
        jlink --add-modules java.base,java.desktop,java.prefs,javafx.base,javafx.controls,javafx.graphics,javafx.swing --output runtime

    - name: Package with jpackage
      run: |
        jpackage --input target --name ForestPixel --main-jar forestpixel-1.0-SNAPSHOT.jar --main-class org.maggdadev.forestpixel.Main --type msi --dest ./build/distributions --runtime-image runtime
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ./build/distributions/ForestPixel-1.0.msi
        name: windows-installer
        retention-days: 1
        overwrite: true
        if-no-files-found: error
